name: Deploy Airtable to Vercel

on:
  push:
    paths:
      - 'apps/airtable/**'
  workflow_dispatch:

env:
  VERCEL_WEBHOOK_URL: https://api.vercel.com/v1/integrations/deploy/prj_FDFdApUzr2MHncpMxIlHiW29piBv/F9tXkqCu8J

jobs:
  trigger-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Webhook
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{}' \
            $VERCEL_WEBHOOK_URL
